/* THIS FILE IS AUTOGENERATED FROM FetchEvent.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_FetchEventBinding_h
#define mozilla_dom_FetchEventBinding_h

#include "EventBinding.h"
#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"
#include "mozilla/dom/Request.h"

namespace mozilla {
namespace dom {

struct FetchEventInitAtoms;
struct NativePropertyHooks;
class ProtoAndIfaceCache;
class Request;

namespace workers {

class FetchEvent;
struct FetchEventAtoms;

} // namespace workers

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

struct FetchEventInit : public EventInit
{
  MOZ_INIT_OUTSIDE_CTOR nsString mClientId;
  MOZ_INIT_OUTSIDE_CTOR bool mIsReload;
  MOZ_INIT_OUTSIDE_CTOR OwningNonNull<mozilla::dom::Request> mRequest;

  FetchEventInit();

  explicit inline FetchEventInit(const FastDictionaryInitializer& )
    : EventInit(FastDictionaryInitializer())
  {
    // Do nothing here; this is used by our "Fast" subclass
  }

  explicit inline FetchEventInit(const FetchEventInit& aOther)
  {
    *this = aOther;
  }

  bool
  Init(JSContext* cx, JS::Handle<JS::Value> val, const char* sourceDescription = "Value", bool passedToJSImpl = false);

  bool
  ToObjectInternal(JSContext* cx, JS::MutableHandle<JS::Value> rval) const;

  void
  TraceDictionary(JSTracer* trc);

  void
  operator=(const FetchEventInit& aOther);

private:
  static bool
  InitIds(JSContext* cx, FetchEventInitAtoms* atomsCache);
};

namespace binding_detail {
struct FastFetchEventInit : public FetchEventInit
{
  inline FastFetchEventInit()
    : FetchEventInit(FastDictionaryInitializer())
  {
    // Doesn't matter what int we pass to the parent constructor
  }
};
} // namespace binding_detail


namespace FetchEventBinding {

  typedef mozilla::dom::workers::FetchEvent NativeType;

  bool
  ConstructorEnabled(JSContext* aCx, JS::Handle<JSObject*> aObj);

  const JSClass*
  GetJSClass();

  bool
  Wrap(JSContext* aCx, mozilla::dom::workers::FetchEvent* aObject, nsWrapperCache* aCache, JS::Handle<JSObject*> aGivenProto, JS::MutableHandle<JSObject*> aReflector);

  template <class T>
  inline JSObject* Wrap(JSContext* aCx, T* aObject, JS::Handle<JSObject*> aGivenProto)
  {
    JS::Rooted<JSObject*> reflector(aCx);
    return Wrap(aCx, aObject, aObject, aGivenProto, &reflector) ? reflector.get() : nullptr;
  }

  void
  CreateInterfaceObjects(JSContext* aCx, JS::Handle<JSObject*> aGlobal, ProtoAndIfaceCache& aProtoAndIfaceCache, bool aDefineOnGlobal);

  JS::Handle<JSObject*>
  GetProtoObjectHandle(JSContext* aCx);

  JS::Handle<JSObject*>
  GetConstructorObjectHandle(JSContext* aCx, bool aDefineOnGlobal = true);

  JSObject*
  GetConstructorObject(JSContext* aCx);

} // namespace FetchEventBinding



} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_FetchEventBinding_h
