/* THIS FILE IS AUTOGENERATED FROM FileReaderSync.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_FileReaderSyncBinding_h
#define mozilla_dom_FileReaderSyncBinding_h

#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

class FileReaderSync;
struct FileReaderSyncAtoms;
struct NativePropertyHooks;
class ProtoAndIfaceCache;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

namespace FileReaderSyncBinding {

  typedef mozilla::dom::FileReaderSync NativeType;

  const JSClass*
  GetJSClass();

  bool
  Wrap(JSContext* aCx, mozilla::dom::FileReaderSync* aObject, JS::Handle<JSObject*> aGivenProto, JS::MutableHandle<JSObject*> aReflector);

  void
  CreateInterfaceObjects(JSContext* aCx, JS::Handle<JSObject*> aGlobal, ProtoAndIfaceCache& aProtoAndIfaceCache, bool aDefineOnGlobal);

  JS::Handle<JSObject*>
  GetProtoObjectHandle(JSContext* aCx);

  JS::Handle<JSObject*>
  GetConstructorObjectHandle(JSContext* aCx, bool aDefineOnGlobal = true);

  JSObject*
  GetConstructorObject(JSContext* aCx);

} // namespace FileReaderSyncBinding



} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_FileReaderSyncBinding_h
