/* THIS FILE IS AUTOGENERATED FROM ServiceWorkerGlobalScope.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_ServiceWorkerGlobalScopeBinding_h
#define mozilla_dom_ServiceWorkerGlobalScopeBinding_h

#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

struct NativePropertyHooks;
class ProtoAndIfaceCache;
class ServiceWorkerGlobalScope;
struct ServiceWorkerGlobalScopeAtoms;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

namespace ServiceWorkerGlobalScopeBinding {

  typedef mozilla::dom::ServiceWorkerGlobalScope NativeType;

  bool
  ConstructorEnabled(JSContext* aCx, JS::Handle<JSObject*> aObj);

  const JSClass*
  GetJSClass();

  bool
  Wrap(JSContext* aCx, mozilla::dom::ServiceWorkerGlobalScope* aObject, nsWrapperCache* aCache, JS::CompartmentOptions& aOptions, JSPrincipals* aPrincipal, bool aInitStandardClasses, JS::MutableHandle<JSObject*> aReflector);

  void
  CreateInterfaceObjects(JSContext* aCx, JS::Handle<JSObject*> aGlobal, ProtoAndIfaceCache& aProtoAndIfaceCache, bool aDefineOnGlobal);

  JS::Handle<JSObject*>
  GetProtoObjectHandle(JSContext* aCx);

  JS::Handle<JSObject*>
  GetConstructorObjectHandle(JSContext* aCx, bool aDefineOnGlobal = true);

  JSObject*
  GetConstructorObject(JSContext* aCx);

} // namespace ServiceWorkerGlobalScopeBinding



} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_ServiceWorkerGlobalScopeBinding_h
