/* THIS FILE IS AUTOGENERATED FROM WorkerGlobalScope.webidl BY Codegen.py - DO NOT EDIT */

#ifndef mozilla_dom_WorkerGlobalScopeBinding_h
#define mozilla_dom_WorkerGlobalScopeBinding_h

#include "ImageBitmapBinding.h"
#include "js/RootingAPI.h"
#include "jspubtd.h"
#include "mozilla/ErrorResult.h"
#include "mozilla/dom/BindingDeclarations.h"
#include "mozilla/dom/Nullable.h"

namespace mozilla {
namespace dom {

struct NativePropertyHooks;
class ProtoAndIfaceCache;
class WorkerGlobalScope;
struct WorkerGlobalScopeAtoms;

} // namespace dom
} // namespace mozilla

namespace mozilla {
namespace dom {

namespace WorkerGlobalScopeBinding {

  typedef mozilla::dom::WorkerGlobalScope NativeType;

  void
  CreateInterfaceObjects(JSContext* aCx, JS::Handle<JSObject*> aGlobal, ProtoAndIfaceCache& aProtoAndIfaceCache, bool aDefineOnGlobal);

  JS::Handle<JSObject*>
  GetProtoObjectHandle(JSContext* aCx);

  JSObject*
  GetProtoObject(JSContext* aCx);

  JS::Handle<JSObject*>
  GetConstructorObjectHandle(JSContext* aCx, bool aDefineOnGlobal = true);

  JSObject*
  GetConstructorObject(JSContext* aCx);

} // namespace WorkerGlobalScopeBinding



} // namespace dom
} // namespace mozilla

#endif // mozilla_dom_WorkerGlobalScopeBinding_h
