/* This file is auto-generated, see gen-scalar-enum.py.  */

#ifndef mozilla_TelemetryScalarEnums_h
#define mozilla_TelemetryScalarEnums_h
namespace mozilla {
namespace Telemetry {
enum class ScalarID : uint32_t {
  BROWSER_ENGAGEMENT_NAVIGATION_ABOUT_NEWTAB,
  BROWSER_ENGAGEMENT_NAVIGATION_ABOUT_HOME,
  BROWSER_ENGAGEMENT_NAVIGATION_SEARCHBAR,
  BROWSER_ENGAGEMENT_NAVIGATION_URLBAR,
  BROWSER_ENGAGEMENT_NAVIGATION_CONTEXTMENU,
  TELEMETRY_TEST_RELEASE_OPTIN,
  TELEMETRY_TEST_UNSIGNED_INT_KIND,
  TELEMETRY_TEST_KEYED_RELEASE_OPTOUT,
  TELEMETRY_TEST_BOOLEAN_KIND,
  TELEMETRY_TEST_KEYED_RELEASE_OPTIN,
  TELEMETRY_TEST_STRING_KIND,
  TELEMETRY_TEST_KEYED_UNSIGNED_INT,
  TELEMETRY_TEST_KEYED_BOOLEAN_KIND,
  TELEMETRY_TEST_RELEASE_OPTOUT,
  TELEMETRY_TEST_UNEXPIRED,
  TELEMETRY_TEST_EXPIRED,
  TELEMETRY_TEST_KEYED_EXPIRED,
  AUSHELPER_WEBSENSE_REG_VERSION,
  BROWSER_ENGAGEMENT_TAB_OPEN_EVENT_COUNT,
  BROWSER_ENGAGEMENT_MAX_CONCURRENT_TAB_COUNT,
  BROWSER_ENGAGEMENT_WINDOW_OPEN_EVENT_COUNT,
  BROWSER_ENGAGEMENT_UNFILTERED_URI_COUNT,
  BROWSER_ENGAGEMENT_TOTAL_URI_COUNT,
  BROWSER_ENGAGEMENT_UNIQUE_DOMAINS_COUNT,
  BROWSER_ENGAGEMENT_MAX_CONCURRENT_WINDOW_COUNT,
  ScalarCount,
};
} // namespace mozilla
} // namespace Telemetry
#endif // mozilla_TelemetryScalarEnums_h

