#pragma warning disable 1591, 1572, 1573
// --------------------------------------------------------------------------------------------
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
// 
// Software distributed under the License is distributed on an "AS IS" basis,
// WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
// for the specific language governing rights and limitations under the
// License.
// --------------------------------------------------------------------------------------------
// Generated by XPIDLImporter from file nsIGeckoScriptBridge.idl
// 
// You should use these interfaces when you access the COM objects defined in the mentioned
// IDL file.
// --------------------------------------------------------------------------------------------
namespace Gecko.Interfaces
{
	using System;
	using System.Runtime.InteropServices;
	using System.Runtime.CompilerServices;
	using SpiderMonkey;
	using Gecko.CustomMarshalers;
	
	
	[ComImport]
	[Guid("40d8fd1b-a2a7-4ff9-afa5-fe30c439d7da")]
	[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
	public interface nsIGeckoFunctionHandler
	{
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant Call([MarshalAs(UnmanagedType.Interface)] nsIVariant proxy, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string aName, [MarshalAs(UnmanagedType.Interface)] nsIVariant thisArg, uint aCount, [MarshalAs(UnmanagedType.LPArray, ArraySubType=System.Runtime.InteropServices.UnmanagedType.Interface, SizeParamIndex=3)] nsIVariant[] aArgs);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIScriptError GetExceptionAttribute();
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		void GetErrorTypeAttribute([MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(AStringMarshaler))] nsAStringBase result);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		void GetErrorMessageAttribute([MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(AStringMarshaler))] nsAStringBase result);
	}
	
	[ComImport]
	[Guid("385542df-f3df-4da9-a407-f9275e2e3ff6")]
	[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
	public interface nsIHarmonyProxyCLRHandler
	{
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetPrototypeOf([MarshalAs(UnmanagedType.Interface)] nsIVariant target);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		void SetPrototypeOf([MarshalAs(UnmanagedType.Interface)] nsIVariant target, [MarshalAs(UnmanagedType.Interface)] nsIVariant prototype);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetOwnPropertyDescriptor([MarshalAs(UnmanagedType.Interface)] nsIVariant target, [MarshalAs(UnmanagedType.Interface)] nsIVariant name);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant OwnKeys([MarshalAs(UnmanagedType.Interface)] nsIVariant target);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool DefineProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant target, [MarshalAs(UnmanagedType.Interface)] nsIVariant name, [MarshalAs(UnmanagedType.Interface)] nsIVariant propertyDescriptor);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool DeleteProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant target, [MarshalAs(UnmanagedType.Interface)] nsIVariant name);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool PreventExtensions([MarshalAs(UnmanagedType.Interface)] nsIVariant target);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool Has([MarshalAs(UnmanagedType.Interface)] nsIVariant target, [MarshalAs(UnmanagedType.Interface)] nsIVariant name);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant Get([MarshalAs(UnmanagedType.Interface)] nsIVariant target, [MarshalAs(UnmanagedType.Interface)] nsIVariant name, [MarshalAs(UnmanagedType.Interface)] nsIVariant receiver);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool Set([MarshalAs(UnmanagedType.Interface)] nsIVariant target, [MarshalAs(UnmanagedType.Interface)] nsIVariant name, [MarshalAs(UnmanagedType.Interface)] nsIVariant val, [MarshalAs(UnmanagedType.Interface)] nsIVariant receiver);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant Enumerate([MarshalAs(UnmanagedType.Interface)] nsIVariant target);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant Apply([MarshalAs(UnmanagedType.Interface)] nsIVariant target, [MarshalAs(UnmanagedType.Interface)] nsIVariant thisValue, [MarshalAs(UnmanagedType.Interface)] nsIVariant args);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant Construct([MarshalAs(UnmanagedType.Interface)] nsIVariant target, [MarshalAs(UnmanagedType.Interface)] nsIVariant args);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool IsExtensible([MarshalAs(UnmanagedType.Interface)] nsIVariant target);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))]
		string ToString();
	}
	
	[ComImport]
	[Guid("9823388e-41fa-11e5-a151-feff819cdc9f")]
	[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
	public interface nsIGeckoScriptBridge
	{
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant EvaluateInWindow([MarshalAs(UnmanagedType.Interface)] nsIDOMWindow window, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string code);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant CreateSandbox([MarshalAs(UnmanagedType.Interface)] nsIVariant global, [MarshalAs(UnmanagedType.Interface)] nsIVariant principal, [MarshalAs(UnmanagedType.U1)] bool wantComponents);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant EvaluateInSandbox([MarshalAs(UnmanagedType.Interface)] nsIVariant sandbox, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string code, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string filename, uint line, [MarshalAs(UnmanagedType.U1)] bool returnAsString);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		void DisposeSandbox([MarshalAs(UnmanagedType.Interface)] nsIVariant sandbox);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant Evaluate([MarshalAs(UnmanagedType.IUnknown)] object global, [MarshalAs(UnmanagedType.Interface)] nsIVariant principal, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string code, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string filename, uint line, [MarshalAs(UnmanagedType.U1)] bool returnAsString);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))]
		string ConvertToString([MarshalAs(UnmanagedType.Interface)] nsIVariant value);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetPrototypeOf([MarshalAs(UnmanagedType.Interface)] nsIVariant obj);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant SetPrototypeOf([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant prototype);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		void PreventExtensions([MarshalAs(UnmanagedType.Interface)] nsIVariant obj);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetOwnPropertyDescriptor([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant name);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetOwnPropertyNames([MarshalAs(UnmanagedType.Interface)] nsIVariant obj);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetOwnPropertySymbols([MarshalAs(UnmanagedType.Interface)] nsIVariant obj);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool HasOwnObjectProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant name);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool IsExtensible([MarshalAs(UnmanagedType.Interface)] nsIVariant obj);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant DefineProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant name, [MarshalAs(UnmanagedType.Interface)] nsIVariant value, [MarshalAs(UnmanagedType.U1)] bool aReadonly, [MarshalAs(UnmanagedType.U1)] bool aEnumerable, [MarshalAs(UnmanagedType.U1)] bool aConfigurable);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		void DefineProperty2([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant name, [MarshalAs(UnmanagedType.Interface)] nsIVariant propertyDescriptor);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant SetProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant name, [MarshalAs(UnmanagedType.Interface)] nsIVariant value);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant name);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant SetItem([MarshalAs(UnmanagedType.Interface)] nsIVariant array, uint index, [MarshalAs(UnmanagedType.Interface)] nsIVariant value);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetItem([MarshalAs(UnmanagedType.Interface)] nsIVariant array, uint index);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		void Dispatch([MarshalAs(UnmanagedType.Interface)] nsIRunnable runnable, [MarshalAs(UnmanagedType.Interface)] nsIDOMWindow window);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant CreateProxy([MarshalAs(UnmanagedType.Interface)] nsIVariant obj);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant DeclareFunction([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant name, [MarshalAs(UnmanagedType.Interface)] nsIGeckoFunctionHandler handler, [MarshalAs(UnmanagedType.U1)] bool aReadonly, [MarshalAs(UnmanagedType.U1)] bool aEnumerable, [MarshalAs(UnmanagedType.U1)] bool aConfigurable);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant Call([MarshalAs(UnmanagedType.Interface)] nsIVariant func, [MarshalAs(UnmanagedType.Interface)] nsIVariant thisArg, uint aCount, [MarshalAs(UnmanagedType.LPArray, ArraySubType=System.Runtime.InteropServices.UnmanagedType.Interface, SizeParamIndex=2)] nsIVariant[] args);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant CallInSandbox([MarshalAs(UnmanagedType.Interface)] nsIVariant sandbox, [MarshalAs(UnmanagedType.Interface)] nsIVariant func, [MarshalAs(UnmanagedType.Interface)] nsIVariant thisArg, uint aCount, [MarshalAs(UnmanagedType.LPArray, ArraySubType=System.Runtime.InteropServices.UnmanagedType.Interface, SizeParamIndex=3)] nsIVariant[] args);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant Create([MarshalAs(UnmanagedType.Interface)] nsIVariant ctor, [MarshalAs(UnmanagedType.Interface)] nsIVariant thisArg, uint aCount, [MarshalAs(UnmanagedType.LPArray, ArraySubType=System.Runtime.InteropServices.UnmanagedType.Interface, SizeParamIndex=2)] nsIVariant[] args);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool DeleteProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant name);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant CreateObject([MarshalAs(UnmanagedType.Interface)] nsIVariant prototype, [MarshalAs(UnmanagedType.Interface)] nsIVariant scope);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant CreateObjectProxy([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.Interface)] nsIVariant scope, [MarshalAs(UnmanagedType.Interface)] nsIHarmonyProxyCLRHandler handler, [MarshalAs(UnmanagedType.U1)] bool overrideToString);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant CreateFunctionProxy([MarshalAs(UnmanagedType.Interface)] nsIVariant func, [MarshalAs(UnmanagedType.Interface)] nsIVariant args, [MarshalAs(UnmanagedType.Interface)] nsIVariant scope, [MarshalAs(UnmanagedType.Interface)] nsIHarmonyProxyCLRHandler handler, [MarshalAs(UnmanagedType.U1)] bool overrideToString);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))]
		string GetType([MarshalAs(UnmanagedType.Interface)] nsIVariant value);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool IsArray([MarshalAs(UnmanagedType.Interface)] nsIVariant value);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetPropertyBySymbolName([MarshalAs(UnmanagedType.Interface)] nsIVariant obj, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string symbolName);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		void Run([MarshalAs(UnmanagedType.Interface)] nsIRunnable runnable);
	}
	
	// <summary>
	// Constants for nsIScriptableComObject ( "4b097fc2-d0e7-4aac-82f9-8f5ec94adf5d" ) interface
	// </summary>
	public sealed class nsIScriptableComObjectConsts
	{
		
		public const int PROPERTY_GETTER = 1;
		
		public const int PROPERTY_GETTER_LISTENER = 2;
		
		public const int PROPERTY_SETTER = 4;
		
		public const int PROPERTY_SETTER_LISTENER = 8;
		
		public const int PROPERTY_DELETE_LISTENER = 16;
	}
	
	[ComImport]
	[Guid("4b097fc2-d0e7-4aac-82f9-8f5ec94adf5d")]
	[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
	public interface nsIScriptableComObject
	{
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		int GetHandlerFlagsAttribute();
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		void Notify([MarshalAs(UnmanagedType.Interface)] nsIVariant proxy, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string action, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string name, [MarshalAs(UnmanagedType.Interface)] nsIVariant args);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool DefineProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant proxy, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string name, [MarshalAs(UnmanagedType.Interface)] nsIVariant value, [MarshalAs(UnmanagedType.Interface)] nsIVariant descriptor);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.U1)]
		bool SetProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant proxy, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string name, [MarshalAs(UnmanagedType.Interface)] nsIVariant value);
		
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType=MethodCodeType.Runtime)]
		[return: System.Runtime.InteropServices.MarshalAs(UnmanagedType.Interface)]
		nsIVariant GetProperty([MarshalAs(UnmanagedType.Interface)] nsIVariant proxy, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef=typeof(WStringMarshaler))] string name);
	}
}
